const ACTION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FEEDS: 'FEEDS',
  POST: 'POST',
  COMMENTS: 'COMMENTS',
  POST_COMMENTS: 'POST_COMMENTS',
  DELETE_COMMENT: 'DELETE_COMMENT',
  TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOADER: 'LOADER'
};
export default ACTION;
