const ACTION = {
  LOGIN: 'LOGIN',
  FEEDS: 'FEEDS',
  POST: 'POST',
  COMMENTS: 'COMMENTS',
  POST_COMMENTS: 'POST_COMMENTS',
  TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
  LOGIN_ERROR: 'LOGIN_ERROR',
};
export default ACTION;
